spring:
  application:
    name: reporting-app
  datasource:
    url: jdbc:mysql://localhost:3306/reporting?useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    username: userrodrigo
    password: userrodrigo
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect